name:                grubber
version:             0.1.0.0
github:              "WorldSEnder/grubber"
license:             BSD-3
author:              "Martin Molzer"
maintainer:          "ga65guy@mytum.de"
copyright:           "2021 Martin Molzer"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            A build system (รก la carte)
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/WorldSEnder/kinded-reflection#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- stm
- dependent-map
- dependent-sum
- dependent-sum-template
- async
- exceptions
- mtl
- reflection
- transformers-base
- monad-control
- constraints
- resourcet
- unliftio-core

ghc-options:
- -Wall

default-extensions:
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- RankNTypes
- TypeFamilies
- TypeOperators
- ScopedTypeVariables

library:
  source-dirs: src

tests:
  grubber-tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - grubber
    - dependent-sum-template
    - HUnit >= 1.6.1 && < 2
    - tasty >= 1.2
    - tasty-hunit
